

# This file was *autogenerated* from the file /work/appendix_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_1 = Integer(1)# Verify the exact example printed in Appendix A.1
R = QQ['x']; (x,) = R._first_ngens(1)
f = x**_sage_const_5  - _sage_const_5 *x - _sage_const_5 
G = f.galois_group()
if isinstance(G, tuple): G = G[_sage_const_0 ]
print("order:", G.order())
print("is_solvable:", G.is_solvable())
print("structure_description:", G.structure_description())
print("discriminant:", f.discriminant())
# show a (3,2) Frobenius pattern
for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ,_sage_const_43 ,_sage_const_47 ]:
    if f.discriminant() % p == _sage_const_0 : continue
    fs = f.change_ring(GF(p)).factor()
    if any(e>_sage_const_1  for _,e in fs): continue
    t = tuple(sorted([P.degree() for P,_ in fs], reverse=True))
    if t == (_sage_const_3 ,_sage_const_2 ):
        print("found (3,2) at p =", p)
        break
print("DONE")

