

# This file was *autogenerated* from the file /work/bring_jerrard.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_12 = Integer(12); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1en6 = RealNumber('1e-6')# Bring-Jerrard / Tschirnhaus with CORRECT Newton power sums.
# Depressed quintic t^5 + p t^3 + q t^2 + r t + s  (e1=0, e2=p, e3=-q, e4=r, e5=-s).
# Correct Newton: for k<=n,  Pk = sum_{j=1}^{k-1} (-1)^(j-1) e_j P_{k-j} + (-1)^(k-1) k e_k
P = PolynomialRing(QQ, 'p,q,r,s')
p, q, r, s = P.gens()
e1, e2, e3, e4, e5 = _sage_const_0 , p, -q, r, -s
e = [e1, e2, e3, e4, e5]
Pk = {_sage_const_0 : _sage_const_5 }
for k in range(_sage_const_1 , _sage_const_12 ):
    if k <= _sage_const_5 :
        acc = sum(((-_sage_const_1 )**(j-_sage_const_1 )) * e[j-_sage_const_1 ] * Pk[k-j] for j in range(_sage_const_1 , k))
        acc += ((-_sage_const_1 )**(k-_sage_const_1 )) * k * e[k-_sage_const_1 ]
        Pk[k] = acc
    else:
        Pk[k] = sum(((-_sage_const_1 )**(j-_sage_const_1 )) * e[j-_sage_const_1 ] * Pk[k-j] for j in range(_sage_const_1 , _sage_const_6 ))
print("CORRECT power sums:")
for k in range(_sage_const_1 , _sage_const_8 ):
    print("  P%d =" % k, Pk[k])
print()

# numeric sanity check at p=1,q=2,r=3,s=4
subs = {p:_sage_const_1 , q:_sage_const_2 , r:_sage_const_3 , s:_sage_const_4 }
T = PolynomialRing(QQ, names=('t',)); (t,) = T._first_ngens(1)
poly = t**_sage_const_5  + _sage_const_1 *t**_sage_const_3  + _sage_const_2 *t**_sage_const_2  + _sage_const_3 *t + _sage_const_4 
roots = poly.change_ring(CDF).roots(multiplicities=False)
print("numeric check at p=1,q=2,r=3,s=4:")
for k in range(_sage_const_1 , _sage_const_8 ):
    num = complex(sum(z**k for z in roots))
    sym = complex(Pk[k].subs(subs))
    print("  P%d: numeric=%.6f  sym=%.6f  match=%s" % (k, num.real, sym.real, abs(num-sym)<_sage_const_1en6 ))
print()

# ---------- Stage 2: quadratic Tschirnhaus  y = x^2 + u x + v ----------
R2 = PolynomialRing(P, 'u,v')
u, v = R2.gens()
# beta = x^2 + u x + v ;  Q1 = sum beta, Q2 = sum beta^2
# Q1 = P2 + u P1 + 5 v
# Q2 = P4 + 2u P3 + (u^2+2v) P2 + 2uv P1 + 5 v^2
Q1 = Pk[_sage_const_2 ] + u*Pk[_sage_const_1 ] + _sage_const_5 *v
Q2 = Pk[_sage_const_4 ] + _sage_const_2 *u*Pk[_sage_const_3 ] + (u**_sage_const_2  + _sage_const_2 *v)*Pk[_sage_const_2 ] + _sage_const_2 *u*v*Pk[_sage_const_1 ] + _sage_const_5 *v**_sage_const_2 
v_sol = ( -Pk[_sage_const_2 ] / _sage_const_5  )          # Q1 = 0 => v
Q2_sub = Q2.subs({v: v_sol})
print("Stage 2 (quadratic Tschirnhaus):")
print("  v =", v_sol)
print("  Q2 after v : degree in u =", Q2_sub.degree(u))
print()

# ---------- Stage 3 (naive): cubic Tschirnhaus  z = x^3 + u x^2 + v x + w ----------
R3 = PolynomialRing(P, 'u,v,w')
u, v, w = R3.gens()
A = PolynomialRing(R3, names=('a',)); (a,) = A._first_ngens(1)
def beta_power_sum(k):
    expr = (a**_sage_const_3  + u*a**_sage_const_2  + v*a + w)**k
    total = _sage_const_0 
    for m in range(_sage_const_0 , _sage_const_3 *k+_sage_const_1 ):
        cm = expr.coefficient(m)
        if cm != _sage_const_0 :
            total += cm * Pk[m]
    return total
Q1c = beta_power_sum(_sage_const_1 )   # = P3 + u P2 + v P1 + 5 w
Q2c = beta_power_sum(_sage_const_2 )
Q3c = beta_power_sum(_sage_const_3 )
w_sol = ( -(Pk[_sage_const_3 ] + u*Pk[_sage_const_2 ] + v*Pk[_sage_const_1 ]) / _sage_const_5  )   # Q1c = 0 => w
E2 = Q2c.subs({w: w_sol})
E3 = Q3c.subs({w: w_sol})
print("Stage 3 (naive cubic Tschirnhaus):")
print("  w =", w_sol)
print("  E2 degree in (u,v):", max(E2.degree(u), E2.degree(v)))
print("  E3 degree in (u,v):", max(E3.degree(u), E3.degree(v)))
res = E2.resultant(E3, v)
print("  resultant in v: degree in u =", res.degree(u))
print()
print("CONCLUSION: with CORRECT power sums, the naive cubic Tschirnhaus")
print("parameter equation has degree %d in the leading parameter." % res.degree(u))
print("DONE")

