# Cycle types of key transitive subgroups of S6 via orbit lengths of
# the cyclic group generated by each element (GAP 4.11 compatible).
Print("GAP version: ", GAPInfo.Version, "\n\n");

CycStr := function( el )
  local orl, s, o;
  orl := List( Orbits( Group( el ), [ 1..6 ] ), Length );
  orl := SortedList( Reversed( orl ) );
  s := "";
  for o in orl do
    s := Concatenation( s, "(", String( o ), ")" );
  od;
  return s;
end;

CycTypes := function( g )
  local cls, rows, r;
  cls := ConjugacyClasses( g );
  rows := Set( List( cls, c -> [ CycStr( Representative( c ) ), Size( c ) ] ) );
  rows := SortedList( rows, function( a, b )
    return a[1] < b[1] or ( a[1]=b[1] and a[2] < b[2] );
  end );
  Print( "  " );
  for r in rows do
    Print( " cyc=", r[1], "  classSize=", r[2], "   " );
  od;
  Print( "\n" );
end;

Print( "6T12 (order 60, 'A5 on 6 points'):\n" ); CycTypes( TransitiveGroup( 6, 12 ) );
Print( "6T7  (S4, natural on 2-subsets):\n" );  CycTypes( TransitiveGroup( 6, 7 ) );
Print( "6T8  (S4, other embedding):\n" );       CycTypes( TransitiveGroup( 6, 8 ) );
Print( "6T14 (order 120, 'S5 on 6 points'):\n" ); CycTypes( TransitiveGroup( 6, 14 ) );
Print( "6T15 (A6):\n" );                        CycTypes( TransitiveGroup( 6, 15 ) );
Print( "6T16 (S6):\n" );                        CycTypes( TransitiveGroup( 6, 16 ) );
Quit();
