

# This file was *autogenerated* from the file /work/enumerate.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_6 = Integer(6)# Drive GAP through the sage gap interface.
# Key: use a SINGLE GAP expression that RETURNs a value (no Print, no local,
# no multi-line), so sage's gap.eval returns the value's string form.
from sage.all import gap

gap.eval("LoadPackage(\"TransGrp\");")

def table(d):
    # AllTransitiveGroups(d) -> list of [group, id]
    expr = ("List(AllTransitiveGroups(%d), "
            "r -> [Size(r[1]), IsSolvableGroup(r[1]), "
            "IsPrimitiveGroup(r[1]), StructureDescription(r[1])])") % d
    val = gap.eval(expr)
    print("=== degree %d ===" % d)
    print(val)
    print()

table(_sage_const_5 )
table(_sage_const_6 )
print("DONE")

