

# This file was *autogenerated* from the file /work/explore_gap.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6)
from sage.all import gap

gap.eval("LoadPackage(\"transgrp\");")

def tgroup_table(d):
    # AllTransitiveGroups(d) is a list of [group, id] pairs
    pairs = gap.eval("AllTransitiveGroups(%d);" % d)
    print("=== Transitive groups of degree %d ===" % d)
    # pairs is a list; get its length
    n = int(gap.eval("Length(%s);" % pairs))
    print("count:", n)
    for i in range(_sage_const_1 , n+_sage_const_1 ):
        g = gap.eval("%s[%d][1]" % (pairs, i))
        order = gap.eval("Size(%s)" % g)
        solv = gap.eval("IsSolvableGroup(%s)" % g)
        # simple?
        simple = gap.eval("IsSimpleGroup(%s)" % g)
        # composition factors
        cf = gap.eval("CompositionSeries(%s);" % g)
        cfstr = gap.eval("List(CompositionSeries(%s), x -> Size(x));" % g)
        print("T%d : order=%s solvable=%s simple=%s comp=%s" % (i, order, solv, simple, cfstr))
    print()

tgroup_table(_sage_const_5 )
tgroup_table(_sage_const_6 )
print("DONE")

