

# This file was *autogenerated* from the file /work/final_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_53 = Integer(53); _sage_const_59 = Integer(59); _sage_const_61 = Integer(61); _sage_const_67 = Integer(67); _sage_const_71 = Integer(71); _sage_const_73 = Integer(73); _sage_const_79 = Integer(79); _sage_const_83 = Integer(83); _sage_const_89 = Integer(89); _sage_const_97 = Integer(97); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_12 = Integer(12); _sage_const_4 = Integer(4)# Final cross-checks (explicit prime list; no primes_first dependency).
import math
R = QQ['x']; (x,) = R._first_ngens(1)
PR = [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ,_sage_const_43 ,_sage_const_47 ,_sage_const_53 ,_sage_const_59 ,_sage_const_61 ,_sage_const_67 ,_sage_const_71 ,_sage_const_73 ,_sage_const_79 ,_sage_const_83 ,_sage_const_89 ,_sage_const_97 ]

def ggroup(f):
    g = f.galois_group()
    if isinstance(g, tuple): g = g[_sage_const_0 ]
    return g

def pat_at(f, p):
    if f.discriminant() % p == _sage_const_0 :
        return None
    F = f.change_ring(GF(p))
    fs = F.factor()
    if any(e > _sage_const_1  for _, e in fs):   # ramified: repeated factor
        return None
    return tuple(sorted([P.degree() for P, _ in fs], reverse=True))

def patterns(f, primes):
    out = []
    for p in primes:
        t = pat_at(f, p)
        if t is not None:
            out.append((p, t))
    return out

print("=== S6 representative x^6-3x^3-3x-3 ===")
f6 = x**_sage_const_6  - _sage_const_3 *x**_sage_const_3  - _sage_const_3 *x - _sage_const_3 
g = ggroup(f6)
print("group:", g.structure_description(), "order", g.order(), "solvable", g.is_solvable())
print("disc:", f6.discriminant(), "is_square:", f6.discriminant() > _sage_const_0  and math.isqrt(f6.discriminant())**_sage_const_2  == f6.discriminant())
found = None
for p in PR:
    t = pat_at(f6, p)
    if t == (_sage_const_2 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ):
        found = p; break
print("transposition (2,1,1,1,1,1) first at p =", found)
print("sample patterns:", patterns(f6, PR[:_sage_const_12 ]))
print("observed cycle-type set:", sorted(set(t for _, t in patterns(f6, PR))))

print()
print("=== A5 quintic x^5-5x^4-5x^3+4x^2+x-5 ===")
f5 = x**_sage_const_5  - _sage_const_5 *x**_sage_const_4  - _sage_const_5 *x**_sage_const_3  + _sage_const_4 *x**_sage_const_2  + x - _sage_const_5 
g5 = ggroup(f5)
print("group:", g5.structure_description(), "order", g5.order(), "solvable", g5.is_solvable())
d5 = f5.discriminant()
print("disc:", d5, "is_square:", d5 > _sage_const_0  and math.isqrt(d5)**_sage_const_2  == d5)
print("sample patterns:", patterns(f5, PR[:_sage_const_12 ]))
ps = set(t for _, t in patterns(f5, PR))
print("observed cycle-type set:", sorted(ps))
print("has (3,1,1,1):", (_sage_const_3 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ) in ps)
print("has (2,2,1):", (_sage_const_2 ,_sage_const_2 ,_sage_const_1 ) in ps)
print("has (5,):", (_sage_const_5 ,) in ps)
print("any odd (transposition (2,1,1,1,1) or (3,2)):", (_sage_const_2 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ) in ps or (_sage_const_3 ,_sage_const_2 ) in ps)
print("DONE")

