

# This file was *autogenerated* from the file /work/hunt_a5_bg.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_50 = Integer(50)# Background A5 quintic search: filter irreducible + square discriminant,
# then compute galois_group() on survivors (far fewer than all), keep A5.
from math import isqrt
import itertools, sys
R = QQ['x']; (x,) = R._first_ngens(1)

def is_square(n):
    n = int(n)
    if n < _sage_const_0 : return False
    r = isqrt(n); return r*r == n

def ggroup(f):
    g = f.galois_group()
    if isinstance(g, tuple): g = g[_sage_const_0 ]
    return g

def frob_cycle(f, p):
    fp = f.change_ring(GF(p))
    if fp == _sage_const_0 : return None
    try: fac = fp.factor()
    except Exception: return None
    degs=[]; ok=True
    for c,e in fac:
        if e>_sage_const_1 : ok=False; break
        degs.append(int(c.degree()))
    return tuple(sorted(degs, reverse=True)) if ok else None

BOX = _sage_const_5 
hits = []
n_checked = _sage_const_0 
for (a4,a3,a2,a1,a0) in itertools.product(range(-BOX,BOX+_sage_const_1 ), repeat=_sage_const_5 ):
    f = x**_sage_const_5  + a4*x**_sage_const_4  + a3*x**_sage_const_3  + a2*x**_sage_const_2  + a1*x + a0
    if not f.is_irreducible():
        continue
    if not is_square(f.discriminant()):
        continue
    n_checked += _sage_const_1 
    g = ggroup(f)
    sd = str(g.structure_description())
    if sd == "A5":
        p3 = None
        for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ,_sage_const_43 ,_sage_const_47 ]:
            if frob_cycle(f,p) == (_sage_const_3 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ):
                p3 = p; break
        hits.append((f, int(f.discriminant()), p3))
        print("A5 HIT: %s  disc=%d  3-cycle@p=%s" % (f, int(f.discriminant()), p3), flush=True)
    if n_checked % _sage_const_50  == _sage_const_0 :
        print("progress: %d square-disc irreducibles checked, %d A5 so far" % (n_checked, len(hits)), flush=True)

print()
print("TOTAL square-disc irreducibles checked:", n_checked)
print("TOTAL A5 found:", len(hits))
if hits:
    f,d,p3 = hits[_sage_const_0 ]
    print()
    print("=== FULL DETAIL: %s ===" % f)
    g = ggroup(f)
    print("order:", g.order(), " solvable:", g.is_solvable(), " sd:", g.structure_description())
    print("disc:", d)
    print("Frobenius patterns:")
    for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ,_sage_const_43 ,_sage_const_47 ]:
        c = frob_cycle(f,p)
        if c: print("  mod %2d: %s" % (p, c))
print("DONE", flush=True)

