

# This file was *autogenerated* from the file /work/hunt_a5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8)# Fast A5 quintic finder.
# Fact: for an irreducible quintic, the transitive subgroups of S5 lying in A5
# are C5, D5, A5. Only A5 contains a 3-cycle. Hence:
#   irreducible  AND  square discriminant  AND  a 3-cycle Frobenius conjugate
#   =>  G = A5   (exactly).
# We use this fast path to search, then confirm the winner with galois_group().
from math import isqrt
import itertools
R = QQ['x']; (x,) = R._first_ngens(1)
GOODP = [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ]

def is_square(n):
    n = int(n)
    if n < _sage_const_0 : return False
    r = isqrt(n); return r*r == n

def has_3cycle(f):
    for p in GOODP:
        fp = f.change_ring(GF(p))
        if fp == _sage_const_0 : continue
        try: fac = fp.factor()
        except Exception: continue
        degs = []
        ok = True
        for c, e in fac:
            if e > _sage_const_1 : ok = False; break
            degs.append(int(c.degree()))
        if ok and tuple(sorted(degs, reverse=True)) == (_sage_const_3 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ):
            return p
    return None

def ggroup(f):
    g = f.galois_group()
    if isinstance(g, tuple): g = g[_sage_const_0 ]
    return g

print("=== search general quintics |coef|<=3 for A5 (fast path) ===")
hits = []
for (a4,a3,a2,a1,a0) in itertools.product(range(-_sage_const_3 ,_sage_const_4 ), repeat=_sage_const_5 ):
    f = x**_sage_const_5  + a4*x**_sage_const_4  + a3*x**_sage_const_3  + a2*x**_sage_const_2  + a1*x + a0
    if not f.is_irreducible():
        continue
    if not is_square(f.discriminant()):
        continue
    p3 = has_3cycle(f)
    if p3 is not None:
        hits.append((f, int(f.discriminant()), p3))
print("fast-path A5 candidates:", len(hits))
for f, d, p3 in hits[:_sage_const_8 ]:
    print("  cand: %s  disc=%d  3-cycle@p=%d" % (f, d, p3))

if hits:
    f = hits[_sage_const_0 ][_sage_const_0 ]
    g = ggroup(f)
    print()
    print("=== CONFIRMATION via galois_group for %s ===" % f)
    print("order:", g.order(), " solvable:", g.is_solvable(),
          " sd:", g.structure_description())
    print("disc:", f.discriminant(), " (square:", is_square(f.discriminant()), ")")
    print("Frobenius patterns:")
    for p in GOODP:
        fp = f.change_ring(GF(p))
        if fp == _sage_const_0 : continue
        try: fac = fp.factor()
        except Exception: continue
        degs=[]; ok=True
        for c,e in fac:
            if e>_sage_const_1 : ok=False; break
            degs.append(int(c.degree()))
        if ok:
            print("  mod %2d: %s" % (p, tuple(sorted(degs, reverse=True))))
print("DONE")

