

# This file was *autogenerated* from the file /work/hunt_a6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_53 = Integer(53); _sage_const_59 = Integer(59); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9)# Targeted A6 sextic finder (fast prefilter + confirm).
# A6 (order 360, degree 6, solvable=False) lies in A6 => square discriminant.
# Its degree-6 action contains 5-cycles (5,1) and double 3-cycles (3,3), but no
# 6-cycles, no single 4-cycles, no transpositions. Distinguishing from the
# transitive A5 (order 60): A5 has single 3-cycles (3,1,1,1) but NOT (3,3).
# Prefilter: irreducible + square disc + a (5,1) pattern + a (3,3) pattern.
from math import isqrt
R = QQ['x']; (x,) = R._first_ngens(1)
P = [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ,_sage_const_43 ,_sage_const_47 ,_sage_const_53 ,_sage_const_59 ]

def is_square(n):
    n=int(n)
    if n<_sage_const_0 : return False
    r=isqrt(n); return r*r==n

def frob(f,p):
    fp=f.change_ring(GF(p))
    if fp==_sage_const_0 : return None
    try: fac=fp.factor()
    except Exception: return None
    degs=[]; ok=True
    for c,e in fac:
        if e>_sage_const_1 : ok=False; break
        degs.append(int(c.degree()))
    return tuple(sorted(degs,reverse=True)) if ok else None

def ggroup(f):
    g=f.galois_group()
    if isinstance(g,tuple): g=g[_sage_const_0 ]
    return g

pool=[]
for a in range(-_sage_const_4 ,_sage_const_5 ):
    for b in range(-_sage_const_4 ,_sage_const_5 ):
        for c in range(-_sage_const_4 ,_sage_const_5 ):
            for d in range(-_sage_const_4 ,_sage_const_5 ):
                for e in range(-_sage_const_4 ,_sage_const_5 ):
                    pool.append(x**_sage_const_6  + a*x**_sage_const_4  + b*x**_sage_const_3  + c*x**_sage_const_2  + d*x + e)
for a in range(-_sage_const_8 ,_sage_const_9 ):
    for b in range(-_sage_const_8 ,_sage_const_9 ):
        for c in range(-_sage_const_8 ,_sage_const_9 ):
            pool.append(x**_sage_const_6  + a*x**_sage_const_3  + b*x + c)

seen=set(); hits=[]; checked=_sage_const_0 
for f in pool:
    if f in seen: continue
    seen.add(f)
    if not f.is_irreducible(): continue
    if not is_square(f.discriminant()): continue
    # need a (5,1) and a (3,3)
    has5=has33=False
    for p in P:
        c=frob(f,p)
        if c is None: continue
        if c==(_sage_const_5 ,_sage_const_1 ): has5=True
        if c==(_sage_const_3 ,_sage_const_3 ): has33=True
        if has5 and has33: break
    if not (has5 and has33): continue
    checked+=_sage_const_1 
    g=ggroup(f)
    sd=str(g.structure_description())
    if sd=="A6":
        hits.append((f,g))
        print("A6 HIT: %s  disc=%d" % (f, int(f.discriminant())), flush=True)
        if len(hits)>=_sage_const_3 : break

print()
print("prefilter candidates checked:", checked, "  A6 hits:", len(hits))
if hits:
    f,g=hits[_sage_const_0 ]
    print()
    print("=== A6 representative: %s ===" % f)
    print("   order=%d solvable=%s disc=%d" % (g.order(), g.is_solvable(), int(f.discriminant())))
    print("   Frobenius patterns:")
    for p in P:
        c=frob(f,p)
        if c: print("     mod %2d: %s" % (p,c))
print("DONE")

