

# This file was *autogenerated* from the file /work/hunt_sextic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_700 = Integer(700); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_200 = Integer(200)# Capped hunt for remaining sextic transitive types: A5, S5, A6, S4.
# Hard cap on galois_group() calls so this always finishes.
R = QQ['x']; (x,) = R._first_ngens(1)
WANT = {"S4":None, "A5":None, "S5":None, "A6":None}
CAP = _sage_const_700 

def ggroup(f):
    g = f.galois_group()
    if isinstance(g, tuple): g = g[_sage_const_0 ]
    return g

def frob_cycle(f, p):
    fp = f.change_ring(GF(p))
    if fp == _sage_const_0 : return None
    try: fac = fp.factor()
    except Exception: return None
    degs=[]; ok=True
    for c,e in fac:
        if e>_sage_const_1 : ok=False; break
        degs.append(int(c.degree()))
    return tuple(sorted(degs, reverse=True)) if ok else None

def detail(f):
    out = {"poly":str(f),"disc":int(f.discriminant()),"frob":{}}
    for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ,_sage_const_31 ,_sage_const_37 ,_sage_const_41 ,_sage_const_43 ,_sage_const_47 ]:
        c = frob_cycle(f,p)
        if c: out["frob"][p]=c
    return out

# Moderate pool: x^6 + a x^4 + b x^3 + c x^2 + d x + e with small coeffs,
# plus x^6 + a x^3 + b x + c.
pool = []
for a in range(-_sage_const_3 ,_sage_const_4 ):
    for b in range(-_sage_const_3 ,_sage_const_4 ):
        for c in range(-_sage_const_3 ,_sage_const_4 ):
            for d in range(-_sage_const_3 ,_sage_const_4 ):
                for e in range(-_sage_const_3 ,_sage_const_4 ):
                    pool.append(x**_sage_const_6  + a*x**_sage_const_4  + b*x**_sage_const_3  + c*x**_sage_const_2  + d*x + e)
for a in range(-_sage_const_6 ,_sage_const_7 ):
    for b in range(-_sage_const_6 ,_sage_const_7 ):
        for c in range(-_sage_const_6 ,_sage_const_7 ):
            pool.append(x**_sage_const_6  + a*x**_sage_const_3  + b*x + c)

seen = set()
checked = _sage_const_0 
for f in pool:
    if checked >= CAP:
        print("CAP reached at %d" % checked, flush=True)
        break
    if f in seen: continue
    seen.add(f)
    if not f.is_irreducible():
        continue
    g = ggroup(f)
    sd = str(g.structure_description())
    checked += _sage_const_1 
    if sd in WANT and WANT[sd] is None:
        WANT[sd] = (f, g)
        print("FOUND %s: %s  (order=%d, solvable=%s)" % (sd, f, g.order(), g.is_solvable()), flush=True)
    if checked % _sage_const_200  == _sage_const_0 :
        print("  ...checked %d, found: %s" % (checked, [k for k,v in WANT.items() if v]), flush=True)

print()
print("checked %d irreducibles (cap %d)" % (checked, CAP))
print()
for sd in ["S4","A5","S5","A6"]:
    if WANT[sd]:
        f, g = WANT[sd]
        d = detail(f)
        print("=== %s : %s ===" % (sd, f))
        print("   order=%d solvable=%s disc=%d" % (g.order(), g.is_solvable(), d["disc"]))
        print("   frob:", d["frob"])
    else:
        print("=== %s : NOT FOUND (cap reached) ===" % sd)
print("DONE")

