

# This file was *autogenerated* from the file /work/probe.sage
from sage.all_cmdline import *   # import sage library

from sage.all import gap
gap.eval("LoadPackage(\"TransGrp\");")

print("A:", repr(gap.eval("2+3")))
print("B:", repr(gap.eval("Length([1,2,3])")))
print("C:", repr(gap.eval("AllTransitiveGroups(5)")))
print("D:", repr(gap.eval("Length(AllTransitiveGroups(5))")))
print("DONE")

