

# This file was *autogenerated* from the file /work/probe2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13)
R = QQ['x']; (x,) = R._first_ngens(1)
f = x**_sage_const_5  - _sage_const_2 *x + _sage_const_2 
g = f.galois_group()
if isinstance(g, tuple): g = g[_sage_const_0 ]

# probe methods
for m in ["structure_description","describe","cycle_type","is_solvable","order"]:
    print(m, "exists:", hasattr(g, m))

print()
print("order:", g.order(), " solvable:", g.is_solvable())
try:
    print("structure_description:", g.structure_description())
except Exception as e:
    print("structure_description failed:", e)
# try permutation group
try:
    P = g.permutation_group()
    print("perm group order:", P.order())
    print("perm group cycle type sample:", P.gens()[_sage_const_0 ])
except Exception as e:
    print("permutation_group failed:", e)

print()
print("discriminant:", f.discriminant())
for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ]:
    fp = f.change_ring(GF(p))
    if fp == _sage_const_0 :
        print("mod %d: zero poly (p divides content)" % p); continue
    fac = fp.factor()
    degs = tuple(sorted([int(e) for c,e in fac]))
    print("mod %d: %s   degrees=%s" % (p, fac, degs))
print("DONE")

