

# This file was *autogenerated* from the file /work/sextics.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_20 = Integer(20)# VERIFIED sextic battery: distinct transitive types with representatives,
# orders, solvability, discriminants, and Frobenius patterns.
R = QQ['x']; (x,) = R._first_ngens(1)
PRIMES = [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ]

def ggroup(f):
    g = f.galois_group()
    if isinstance(g, tuple): g = g[_sage_const_0 ]
    return g

def frob_cycle(f, p):
    fp = f.change_ring(GF(p))
    if fp == _sage_const_0 : return None
    try: fac = fp.factor()
    except Exception: return None
    degs=[]; ok=True
    for c,e in fac:
        if e>_sage_const_1 : ok=False; break
        degs.append(int(c.degree()))
    return tuple(sorted(degs, reverse=True)) if ok else None

def classify(f, label):
    if not f.is_irreducible():
        return None
    g = ggroup(f)
    out = {"label":label,"poly":str(f),"order":int(g.order()),
           "solv":bool(g.is_solvable()),"sd":str(g.structure_description()),
           "disc":int(f.discriminant()),"frob":{}}
    for p in PRIMES:
        c = frob_cycle(f,p)
        if c is not None:
            out["frob"][p]=c
    return out

def scan(family, tag):
    seen={}; rows=[]
    for f,lab in family:
        c = classify(f,lab)
        if c is None: continue
        rows.append(c)
        if c["sd"] not in seen:
            seen[c["sd"]] = c
    return rows, seen

print("################  SEXTICS  ################")
# Bring-Jerrard sextic family x^6 + a*x^3 + b*x + c  and  x^6 + a*x + b
Fam = []
# x^6 + a*x^3 + b*x + c
for a in range(-_sage_const_3 ,_sage_const_4 ):
    for b in range(-_sage_const_3 ,_sage_const_4 ):
        for c in range(-_sage_const_3 ,_sage_const_4 ):
            Fam.append((x**_sage_const_6  + a*x**_sage_const_3  + b*x + c, "BJ6(a=%d,b=%d,c=%d)"%(a,b,c)))
# x^6 + a*x + b
for a in range(-_sage_const_6 ,_sage_const_7 ):
    for b in range(-_sage_const_6 ,_sage_const_7 ):
        Fam.append((x**_sage_const_6  + a*x + b, "BJ6b(a=%d,b=%d)"%(a,b)))
# general sextics
GEN6 = [
    x**_sage_const_6  - _sage_const_5 *x**_sage_const_4  + _sage_const_5 *x**_sage_const_2  - _sage_const_1 ,
    x**_sage_const_6  - _sage_const_2 *x**_sage_const_5  + _sage_const_3 *x**_sage_const_4  - _sage_const_3 *x**_sage_const_3  + _sage_const_2 *x**_sage_const_2  - x + _sage_const_1 ,
    x**_sage_const_6  + x**_sage_const_5  - _sage_const_5 *x**_sage_const_4  - _sage_const_4 *x**_sage_const_3  + _sage_const_4 *x**_sage_const_2  + _sage_const_3 *x - _sage_const_2 ,
    x**_sage_const_6  - _sage_const_3 *x**_sage_const_5  + _sage_const_3 *x**_sage_const_4  + _sage_const_2 *x**_sage_const_3  - x**_sage_const_2  - _sage_const_2 *x + _sage_const_1 ,
    x**_sage_const_6  - _sage_const_4 *x**_sage_const_5  + _sage_const_6 *x**_sage_const_4  - _sage_const_4 *x**_sage_const_3  + _sage_const_2 *x**_sage_const_2  - x + _sage_const_1 ,
    x**_sage_const_6  + _sage_const_2 *x**_sage_const_5  - _sage_const_3 *x**_sage_const_4  + x**_sage_const_3  + _sage_const_2 *x - _sage_const_5 ,
    x**_sage_const_6  - _sage_const_7 *x**_sage_const_5  + _sage_const_14 *x**_sage_const_4  - _sage_const_7 *x**_sage_const_3  + _sage_const_7 *x**_sage_const_2  - _sage_const_2 *x + _sage_const_1 ,
    x**_sage_const_6  - _sage_const_6 *x**_sage_const_5  + _sage_const_15 *x**_sage_const_4  - _sage_const_20 *x**_sage_const_3  + _sage_const_15 *x**_sage_const_2  - _sage_const_6 *x + _sage_const_2 ,
]
GEN6 = [(f,"gen6_%d"%(i+_sage_const_1 )) for i,f in enumerate(GEN6)]
Fam = Fam + GEN6

rows, seen = scan(Fam, "6")
print("Distinct transitive types found among %d irreducible sextics:" % len(rows))
for sd,c in sorted(seen.items(), key=lambda kv: kv[_sage_const_1 ]["order"]):
    print("  %-16s order=%-4d solvable=%-5s  example: %s  poly=%s"
          % (sd, c["order"], c["solv"], c["label"], c["poly"]))
print()
print("Representatives (with Frobenius patterns):")
for sd,c in sorted(seen.items(), key=lambda kv: kv[_sage_const_1 ]["order"]):
    print("  %s | order=%d solv=%s | disc=%d" % (sd, c["order"], c["solv"], c["disc"]))
    print("    %s" % c["poly"])
    print("    frob:", c["frob"])
print()
print("DONE6  (irreducibles: %d, distinct types: %d)" % (len(rows), len(seen)))

