

# This file was *autogenerated* from the file /work/test_basic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)# Basic Sage sanity test: Galois group computation
R = QQ['x']; (x,) = R._first_ngens(1)

def ggroup(f):
    g = f.galois_group()
    if isinstance(g, tuple):
        g = g[_sage_const_0 ]
    return g

f1 = x**_sage_const_5  - x**_sage_const_4  - _sage_const_4 *x**_sage_const_3  + _sage_const_3 *x**_sage_const_2  + _sage_const_3 *x - _sage_const_1 
print("f1 =", f1)
print("f1 irreducible:", f1.is_irreducible())
G1 = ggroup(f1)
print("f1 galois group order:", G1.order())
print("f1 solvable:", G1.is_solvable())
print()

f2 = x**_sage_const_5  + x**_sage_const_4  - _sage_const_4 *x**_sage_const_3  - _sage_const_3 *x**_sage_const_2  + _sage_const_3 *x + _sage_const_1 
print("f2 =", f2)
print("f2 irreducible:", f2.is_irreducible())
G2 = ggroup(f2)
print("f2 galois group order:", G2.order())
print("f2 solvable:", G2.is_solvable())
print()

f3 = x**_sage_const_5  - _sage_const_2 *x + _sage_const_2 
print("f3 =", f3)
print("f3 irreducible:", f3.is_irreducible())
G3 = ggroup(f3)
print("f3 galois group order:", G3.order())
print("f3 solvable:", G3.is_solvable())
print()

print("DONE")

