

# This file was *autogenerated* from the file /work/verify_sage_api.sage
from sage.all_cmdline import *   # import sage library

_sage_const_40 = Integer(40); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_12 = Integer(12); _sage_const_6 = Integer(6)# Label all verified representatives via NumberField.galois_group().transitive_label()
# (the API the review cites) and pair with the polynomial-API structure description.
R = QQ['x']; (x,) = R._first_ngens(1)

def label_of(f):
    lab = None
    try:
        K = NumberField(f, names=('a',)); (a,) = K._first_ngens(1)
        G = K.galois_group()
        lab = G.transitive_label()
    except Exception as e:
        lab = "ERR:" + repr(e)[:_sage_const_40 ]
    # structure description + order from the polynomial API (robust)
    g2 = f.galois_group()
    if isinstance(g2, tuple): g2 = g2[_sage_const_0 ]
    sd = g2.structure_description()
    return (lab, sd, g2.order(), g2.is_solvable())

QU = {
 "C5":  x**_sage_const_5  + x**_sage_const_4  - _sage_const_4 *x**_sage_const_3  - _sage_const_3 *x**_sage_const_2  + _sage_const_3 *x + _sage_const_1 ,
 "D10": x**_sage_const_5  - _sage_const_5 *x + _sage_const_12 ,
 "F20": x**_sage_const_5  - _sage_const_5 ,
 "A5":  x**_sage_const_5  - _sage_const_5 *x**_sage_const_4  - _sage_const_5 *x**_sage_const_3  + _sage_const_4 *x**_sage_const_2  + x - _sage_const_5 ,
 "S5":  x**_sage_const_5  - _sage_const_5 *x - _sage_const_5 ,
}
SE = {
 "C6":      x**_sage_const_6  - x**_sage_const_3  + _sage_const_1 ,
 "S3":      x**_sage_const_6  + _sage_const_3 ,
 "D12":     x**_sage_const_6  - _sage_const_3 *x**_sage_const_3  - _sage_const_1 ,
 "C3xS3":   x**_sage_const_6  - _sage_const_3 *x**_sage_const_3  + _sage_const_3 ,
 "S3xS3":   x**_sage_const_6  - _sage_const_3 *x**_sage_const_3  - _sage_const_3 ,
 "C2xS4":   x**_sage_const_6  - _sage_const_3 *x + _sage_const_5 ,
 "W72":     x**_sage_const_6  - _sage_const_3 *x + _sage_const_3 ,
 "A6":      x**_sage_const_6  - _sage_const_4 *x**_sage_const_4  - x**_sage_const_3  - _sage_const_3 *x**_sage_const_2  + _sage_const_4 *x - _sage_const_1 ,
 "S6":      x**_sage_const_6  - _sage_const_3 *x**_sage_const_3  - _sage_const_3 *x - _sage_const_3 ,
}
print("### transitive_label (NumberField API) | structure_description | order | solvable ###")
for name, f in QU.items():
    print("Q", name, "->", label_of(f))
for name, f in SE.items():
    print("S", name, "->", label_of(f))
print("DONE")

